### PR TITLE
Update definitions.json to be more clearly worded.

### PR DESCRIPTION
**Pull request by RichardoC**
Updated based on comments on PR #20, this should make it clearer that the secured one is desired.

### CODE REVIEW

**Comment by paul-ion** [comment]
Thank you @RichardoC ! How about: "Which of the following code snippets prevents a command injection vulnerability?"

**Comment by RichardoC** [comment]
I'm not sure about phrasing it that way, a change in code or refactor prevents a vulnerability. What you're getting them to do is to chose code which doesn't contain that vulnerability?

**Comment by paul-ion** [comment]
Yes the idea is that input whitelisting should be used whenever possible to prevent vulnerabilities.

**Comment by RichardoC** [comment]
Glad you agree, so are you happy with this PR?

**Comment by paul-ion** [comment]
@RichardoC the PR proposes a negative approach: "select which code **doesn't contain** a vulnerability". 

The existing text asks "select which code **prevents** a vulnerability" which is the line with the intent of demonstrating that input validation should be used whenever possible to prevent vulnerabilities.

**Pull request closed without merging**
